# Generated by Django 4.1.3 on 2023-03-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='name',
            field=models.CharField(default='a', max_length=500),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
