# Generated by Django 4.1.3 on 2023-03-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_wishlist_name_wishlist_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image_product',
            field=models.ImageField(default='store/img/img_coming_soon.png', upload_to='store/img'),
        ),
    ]
