# Generated by Django 4.1.3 on 2023-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='img',
            field=models.ImageField(default='store/img/img_coming_soon.png', upload_to='store/img'),
        ),
    ]
