# Generated by Django 4.1.3 on 2023-03-03 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sub',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
