# Generated by Django 4.1.3 on 2023-03-04 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_1',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_2',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_3',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_4',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_5',
        ),
        migrations.RemoveField(
            model_name='image',
            name='img_6',
        ),
        migrations.AddField(
            model_name='image',
            name='name_product',
            field=models.CharField(default='', max_length=500),
        ),
    ]
