# Generated by Django 4.1.3 on 2023-03-04 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_rename_img_1_image_img_remove_image_img_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image_product',
        ),
    ]
