# Generated by Django 4.1.3 on 2023-03-07 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={},
        ),
    ]
