# Generated by Django 4.1.3 on 2023-03-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('-public_day',)},
        ),
    ]
