# Generated by Django 4.1.3 on 2023-03-09 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='size',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
