# Generated by Django 4.1.3 on 2023-03-14 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
