# Generated by Django 4.1.3 on 2023-03-15 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
