# Generated by Django 4.1.3 on 2023-03-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='vote',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
