# Generated by Django 4.1.3 on 2023-03-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_product_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='vote',
            field=models.FloatField(blank=True, default=5, null=True),
        ),
    ]
