# Generated by Django 4.1.3 on 2023-03-22 00:22

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_star'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='describe',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
