# Generated by Django 4.1.3 on 2023-03-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_orderitem_color_orderitem_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='vote',
            field=models.IntegerField(blank=True, default=5, max_length=2, null=True),
        ),
    ]
