# Generated by Django 4.1.3 on 2023-03-17 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitem_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='vote',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
